- hosts: all
  become: true
  gather_facts: false
  tasks:
  - name: "create new deployment"
    command: kubectl create -f /home/ubuntu/Deployment.yml
  - name: "create new sercices"
    command: kubectl create -f /home/ubuntu/Service.yml
